sources:
  oauth2-proxy:
    kind: helmchart
    spec:
      url: https://oauth2-proxy.github.io/manifests/
      name: oauth2-proxy
      versionFilter:
        kind: semver
        pattern: '*'
conditions: {}
targets:
  oauth2-proxy:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/steampipe/Chart.yaml
      key: $.dependencies[0].version
    sourceid: oauth2-proxy
