sources:
  steampipe:
    kind: githubrelease
    spec:
      owner: "devops-ia"
      repository: "steampipe"
      token: {{ requiredEnv "GITHUB_TOKEN" }}
      versionFilter:
        kind: semver
        pattern: ">=v2.0.0"
conditions: {}
targets:
  chartVersion:
    name: bump appversion
    kind: helmchart
    spec:
      name: charts/steampipe
      file: Chart.yaml
      key: $.appVersion
      versionincrement: patch
    sourceid: steampipe
