sources:
  oauth2-proxy:
    kind: dockerimage
    spec:
      image: ghcr.io/oauth2-proxy/charts/oauth2-proxy
      architecture: linux/amd64
      versionFilter:
        kind: semver
        pattern: '*' # replace with CI/CD updatecli
    sourceid: oauth2-proxy
conditions: {}
targets:
  oauth2-proxy:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: charts/Chart.yaml
      key: $.dependencies[0].version
    sourceid: oauth2-proxy
