sources:
  steampipe:
    kind: githubrelease
    spec:
      owner: "devops-ia"
      repository: "steampipe"
      token: {{ requiredEnv "GITHUB_TOKEN" }}
      versionFilter:
        kind: semver
        pattern: ">=v2.0.0"
conditions: {}
targets:
  appVersion:
    name: bump appVersion
    kind: helmchart
    spec:
      name: charts/steampipe
      file: Chart.yaml
      key: $.appVersion
    sourceid: steampipe
  chartVersion:
    name: bump chart version
    kind: helmchart
    spec:
      name: charts/steampipe
      file: Chart.yaml
      key: $.version
    sourceid: steampipe
    transformers:
      - trimprefix: "v"
