sources:
  steampipe:
    kind: githubrelease
    spec:
      owner: "turbot"
      repository: "steampipe"
      token: {{ requiredEnv "GITHUB_TOKEN" }}
      versionFilter:
        kind: semver
    transformers:
      - trimprefix: "v"
conditions: {}
targets:
  chartVersion:
    name: bump appversion
    kind: yaml
    spec:
      file: charts/Chart.yaml
      key: $.appVersion
