sources:
  powerpipe:
    kind: githubrelease
    spec:
      owner: "turbot"
      repository: "powerpipe"
      token: {{ requiredEnv "GITHUB_TOKEN" }}
      versionFilter:
        kind: semver
    transformers:
      - trimprefix: "v"
conditions: {}
targets:
  powerpipeImageTag:
    name: bump powerpipe image tag in values.yaml
    kind: yaml
    spec:
      file: charts/steampipe/values.yaml
      key: $.powerpipe.image.tag
    sourceid: powerpipe
