name: Bug report
description: Create a bug report
title: "[steampipe] Bug title"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: Please be cautious with the sensitive information/logs while filing the issue.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug a clear and concise description of what the bug is.
    validations:
      required: true

  - type: input
    id: helm-version
    attributes:
      label: What's your helm version?
      description: Output of `#~ helm version`
    validations:
      required: true

  - type: input
    id: kubectl-version
    attributes:
      label: What's your kubectl version?
      description: Output of `#~ kubectl version`
    validations:
      required: true

  - type: input
    id: chart-version
    attributes:
      label: Chart version
      description: Enter the version of the chart that you encountered this bug.
    validations:
      required: true

  - type: textarea
    id: explain-bug
    attributes:
      label: Explain bug
      description: Explain what happened.
    validations:
      required: false

  - type: textarea
    id: expected-result
    attributes:
      label: What you expected to happen?
      description: Enter what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: reproduce-bug
    attributes:
      label: How to reproduce it?
      description: Explain step-by-step if is possible.
    validations:
      required: false

  - type: textarea
    id: chart-values
    attributes:
      label: Enter the changed values of values.yaml?
      description: Please enter only values which differ from the defaults. Enter `NONE` if nothing's changed.
      placeholder: "key: value"
    validations:
      required: false

  - type: textarea
    id: helm-command
    attributes:
      label: Enter the command that you execute when chart failing/misfunctioning
      description: Enter the command as-is as how you executed.
      placeholder: helm install [RELEASE] steampipe/steampipe --version [VERSION] -f values.yaml --debug
    validations:
      required: true

  - type: textarea
    id: more-info
    attributes:
      label: More info
    validations:
      required: false
