name: Auto assign
on:
  issues:
    types: [opened, edited, synchronize, reopened]
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: amartingarcia
          numOfAssignee: 1
